/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablero;


import pieces.Shapes;

import java.awt.*;

public class Tablero extends javax.swing.JFrame {

    // cambiar este valor para dimensiones
    static int COLUMNAS_X = 10;
    static int FILAS_Y = 20;
    private static int DIMENSION = 30;
    
    //la columna posucionado
    private int index_x = 5;
    
    // Tablero con objetos JButton
    public MyJLabel[][] tableroLabels = new MyJLabel[COLUMNAS_X][FILAS_Y];
    private ThreadFigura threadFigura;
    private Shapes shapes;
    
    Tablero() {
        initComponents();
        generarTablero();
        threadFigura = new ThreadFigura(this);
    }
    
    private void generarTablero(){
    for(int i=0;i<COLUMNAS_X;i++)
        for(int j=0;j<FILAS_Y;j++)
        {
                // coloca imagen a todos vacio
                tableroLabels[i][j] = new MyJLabel();


                panelTablero.add(tableroLabels[i][j].label);
                // coloca dimensiones y localidad
                tableroLabels[i][j].label.setBounds(DIMENSION*i, DIMENSION*j, DIMENSION, DIMENSION);

                panelTablero.setSize(DIMENSION*COLUMNAS_X, DIMENSION*FILAS_Y);
        }
    }
    
    int getIndex_x(){
        return this.index_x;
    }    
    private void decrementIndex_x(){
        threadFigura.setMoveLeft(true);

    }
    private void incrementIndex_x(){
        threadFigura.setMoveRight(true);
    }

    void setIndex_x(int index_x) {
        this.index_x = index_x;
    }

    void setShapes(Shapes shapes) {
        this.shapes = shapes;
    }

    void checkBottom(){
        int linesFilled = 0;
        for (int i = FILAS_Y-1; i>0; i--){
            boolean bottomFilled = false;
            for(int j=0;j<COLUMNAS_X;j++){
                bottomFilled = tableroLabels[j][i].isFilled();
                if(!bottomFilled){
                    break;
                }
            }

            if (bottomFilled){
                System.out.println("BOTTOM FILLED");
                linesFilled++;
            } else {
                break;
            }
        }

        if(linesFilled>0){
            int displacement = linesFilled;
            for (int i = FILAS_Y-1; i>0; i--){
                for(int j=0;j<COLUMNAS_X;j++){
                    if(linesFilled>0){
                        tableroLabels[j][i].setFilled(false).label.setBackground(Color.DARK_GRAY);
                    } else {
                        tableroLabels[j][i+displacement].setFilled(true).label.setBackground(tableroLabels[j][i].label.getBackground());
                        tableroLabels[j][i+displacement].setFilled(false).label.setBackground(Color.DARK_GRAY);
                    }
                }
                if(linesFilled>0){
                    linesFilled--;
                }
            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnLEFT = new javax.swing.JButton();
        brtRIGHT = new javax.swing.JButton();
        btnVelocidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTablero.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLEFT.setText("<< LEFT");
        btnLEFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLEFTActionPerformed(evt);
            }
        });

        brtRIGHT.setText("RIGHT >>");
        brtRIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtRIGHTActionPerformed(evt);
            }
        });

        btnVelocidad.setText("+");
        btnVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelocidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnLEFT)
                        .addGap(178, 178, 178)
                        .addComponent(brtRIGHT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(196, 196, 196)
                        .addComponent(btnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLEFT)
                            .addComponent(brtRIGHT))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        threadFigura.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLEFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLEFTActionPerformed
        // TODO add your handling code here:
        decrementIndex_x();
    }//GEN-LAST:event_btnLEFTActionPerformed

    private void brtRIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtRIGHTActionPerformed
        // TODO add your handling code here:
        incrementIndex_x();
    }//GEN-LAST:event_brtRIGHTActionPerformed

    private void btnVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelocidadActionPerformed
        // TODO add your handling code here:
        threadFigura.decrementVelocidad();
    }//GEN-LAST:event_btnVelocidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtRIGHT;
    private javax.swing.JButton btnLEFT;
    private javax.swing.JButton btnVelocidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables

    //kjdgsvflkjhsbv,jiklweu

}
